language: go

go:
  - 1.6.3
  - 1.7
  - tip

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
  allow_failures:
    - go: tip

script:
  - go fmt ./...
  - go test -v -race ./util/

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.7" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then ./scripts/cross_compile.sh; ghr --username wallyqs --token $GITHUB_TOKEN --replace --debug $TRAVIS_TAG pkg/ ; fi
